### ISSUE TITLE
Where file thuvientiengviettonghop.txt ?

### ISSUE THREAD

**Issue by kimson11025** [hoangks5/danh-dau-cau-tiengviet#1]
i can download file ?

**Comment by hoangks5** [comment]
https://docs.google.com/presentation/d/19Pl4gQtGNXmJ_QyDZ6pzAz6eYPduE8qGkOxbJkEb80c/edit?usp=sharing

**Comment by kimson11025** [comment]
> https://docs.google.com/presentation/d/19Pl4gQtGNXmJ_QyDZ6pzAz6eYPduE8qGkOxbJkEb80c/edit?usp=sharing

thanks

**Comment by kimson11025** [comment]
done

**Comment by kimson11025** [comment]
> https://docs.google.com/presentation/d/19Pl4gQtGNXmJ_QyDZ6pzAz6eYPduE8qGkOxbJkEb80c/edit?usp=sharing

**Comment by kimson11025** [comment]
> https://docs.google.com/presentation/d/19Pl4gQtGNXmJ_QyDZ6pzAz6eYPduE8qGkOxbJkEb80c/edit?usp=sharing

done
